= Everything You Need to Know to Grow Open Source
Dan Allen <http://opendevise.io>
:track: Startup

[abstract]
--
//tag::abstract[]
How do you grow an open source software project?
How do you get to 100 contributors, 1,000 community members, 10,000 users or 100,000 downloads?
How do you make it wildly successful?

I've helped cultivate wildly successful open source communities on sparse budgets.
Today, I want to share with you the rules I follow to build open source projects and communities.

Open Source works because it's the right way.
Open Source works because it's the best way.
There are no secrets that, once revealed, bring it all crashing down.
Even with the cards face up on the table, we still feel good when someone thanks us for our contribution.
When they don't, we might decide to vote with our feet and leave.

Attend this talk to learn everything you need to know about Open Source to make your community building efforts wildly successful.
//end::abstract[]
--

== View slides locally

This deck is a http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation.
To run it, first ensure you have the following installed:

. http://nodejs.org[Node.js]
. http://bower.io[Bower]:

 $ npm install -g bower

. http://gulpjs.com[Gulp]:

 $ npm install -g gulp

Then, install dependencies and run the preview server:

```bash
$ npm install && bower install
$ gulp serve
```

Finally, visit \http://localhost:8080 in your browser.
