////
.TODO
* consolidate ending
* made revisions to Bartosz story to make it more conversational
* review commented lines (put asterisk in front of candidate dialog for inclusion)
* Faces, faces, faces
* builds resilience in community

* Build the story you want your users to tell.
* slide for "Be transparent"
* read Bartosz' blog / watch Bartosz's talk
* start with "developers want to work on open source" tweet / quote?
* be selfless
* if software is eating the world, open source is feeding it

* ideas that spread win (Seth Godin and similar quote from resonate)
* Community members learn from each other
* People are driven to communicate
* Weave in *devotion* to the conclusion
* Where does the "Choose Civility" banner come in?
* Picture of developer on mountain hike w/ coworker instead of community member
* http://www.wired.com/2015/07/open-source-going-even-openbecause/
* https://speakerdeck.com/matthewmccullough/patterns-for-collaborative-software-development-in-a-social-world-at-javaone-2015

.Runs
. 16:30
////
= Everything You Need to Know to Grow Open Source
ifdef::env-browser[:toc: macro]

ifdef::backend-pdf[]
[abstract]
--
include::../../README.adoc[tag=abstract]
--

<<<
endif::[]

ifeval::["{toc-placement}" == "macro"]
toc::[]
endif::[]

== Introduction

//!SLIDE title
Open Source is a no-brainer.

//!SLIDE brain-creativity
Actually, it's not.
It requires quite a bit of brain power.
Creating Open Source software and building a community around it is hard and doesn't come for free.
In fact, it's a daily duty.
It takes investment, both in the form of time and money.
But with all things that produce value, it's totally worth doing.

Open Source is the best model we've found to produce software.
If you do it well, you have a lot to gain.
Do it poorly and what you unleash onto the world amounts to little more than a code dump.

So how do you do it?
How do you give your project that spark?
How do you make it grow?

//SLIDE! Arquillian invasion backdrop
I've cultivated several very successful open source communities on sparse budgets.
Each experience has taught me lessons that I'm sharing with you today.
I hope you'll be able to use this advice to make your community building efforts wildly successful.
After all, not many companies do (OSS well).

//Above all, people are attracted to ”a shared purpose that is clearly understood”, so let's start there.
//That's what gets people out of bed in the morning.

:sectnums:

// P = purpose
== Have a purpose
// criteria for success?

How many projects have you come across that make you go, “What the heck is this for?”
_Don't be that project._
//What's your purpose?
Find your purpose.
Why does your project exist?

//!SLIDE Raison d'être bottle
Perhaps it goes without saying, but if you want to grow, you need to have an effort that's worth joining.
And people need to know what it is.
//A purpose.
People need a change they can believe in.
A sense of purpose.
A rally call.
A raison d'être.
They want to be able to achieve something bigger than what they can achieve by themselves.
(And escape senseless office politics for a while).
//Community creates for them a shared sense of identity & purpose where they can share value with one another.

//!SLIDE A*M*P
Open Source is created by people.
To grow Open Source, you need to understand what drives people.
You need to AMP them up.
In his book Drive, Dan Pink identifies three key factors that drive people.

//!SLIDE Autonomy - Mastery - Purpose
[verse]
AMP = Autonomy, mastery, purpose.

Participation in open source is voluntary.
Remember and respect that.
But also recognize that people aren't working for free.
Thinking that would be naive.
They just aren't working for direct financial gain, the traditional model.
They're driven by something else.
People participate to do what they enjoy far away from what they don't.
They participate to learn from each other and grow.
They work for fulfillment...at least your audience does.

You need to craft a call to adventure for people.
Your mission becomes a story; your story.
It shapes the culture of your community.
It serves as a filter to help you decide what to do, what not to do and who your audience even is.

//!SLIDE Dogfish Head slogan
Dogfish Head, for example, has a great tagline:

""
Off-centered ales for off-centered people.
""

Notice how the tagline communicates a purpose (what they want to achieve), a filter (what to do, what not do) and an identity (who they target).
That's the stuff that gets people behind you, gets them involved and gives you focus.
It's a call to adventure.
Without it, you don't get noticed.
People just pass you by.
//Without a purpose and a future, you have no project; people abandon a sinking ship
//It also helps you weather changes and shifts.
Have a purpose and communicate it.

== Be present and communicate

. Communicate your purpose
. Be responsive & listen
. Don't be l33T (don't alienate them)
. Be transparent

[discrete]
=== Communicate your purpose

Brilliant software alone isn't enough to get people to act.
You need to communicate your idea.
Only ideas that spread win.
And your idea will be judged--at least initially--on how well you perform that communication.

"In a society that values speech free from esoteric, incomprehensible bullshit, speaking in jargon carries penalties."
-- Carmine Gallo

Your message needs to be organized, authentic and empathetic.
Plant the idea in their minds and in their hearts.

To build a community, you need to communicate your purpose, but you also need to show up and interact with them.
//You can't build a community if you don't show up, interact with them & communicate your purpose.

[discrete]
=== Be responsive and listen

No activity signals a dead project.
And every project starts out as a ghost town.
People kick things, they show aggression towards things, that they think are dead.
And that's not good for growth.
The way to avoid this from happening is to be constantly be engaging people.
Communicate with the community.
Be on.
Be everywhere.
Communicate openly to a fault.
Take the time to meet with them; get to know them.
//I make it a point to know the names as well as the usernames of all my community members.
Make them feel like you have all the time in the world for them...even if you don't.
Make each person the center of your attention when you're interacting with them.
//When you connect with them, they will give you the benefit of the doubt.
(And yes, you'll need to work at it).

Communication is the water that your project and your community needs to grow.
It's the synapse of OSS.
Make communication flow readily throughout your project.

Communication is also 2-way.
LISTEN TO THEM!
They hold the secret to what can make you great.
That's because the intelligence of a project is in the collective thinking.
Power in numbers.
// TODO slide for GitHub issues
To realize that power, communication must be easy; and it's even better if it is contextual (e.g., GitHub issues).
//...because you can have a lot of little discussions without filling up everyone's inbox; allows you to communicate more

"What's relevant to a [community] is how well people are communicating their ideas, and how well they're cooperating, not how clever the individuals are."
-- Matt Ridley

// FIXME still an awkward section; need to rethink placement
[discrete]
=== Don't be l33T
// not holding information hostage

// QUESTION move power in numbers here?

*Show that you want them.
Show that you actually _want_ to grow.*
Make the communication personal.
//But don't underestimate the power of the persontal interactions, esp face-to-face.
For instance, the effect of a single face-to-face meetup can last for years.
It's individuals that add up to make a community.
Lack of information?
Don't let it create barriers between you and them.
Missing or weak documentation is a major barrier for the success of the project and growth of the community.
Respect their time & space by giving them the information they need.
Be glad that they came and shared an irretrievable slice of their life with your project.
//Check your ego at the door.

//SLIDE! +1
Communication doesn't necessarily mean lots of words.
Communication can be terse and still be very effective.
That's power of the +1.
//:beers: also works
It not only says, “I'm present and I support this,” it also provides encouragement, which we'll talk about a bit later.
You can also can communicate simply through commits of docs and code.
// SLIDE IDEA: screenshot partial of "last commit X days ago"
All this externally signals, “this project is being maintained.”

[discrete]
=== Be transparent

// FIXME missing a slide
The most important thing in OSS is to be honest, transparent and frank.
Be real.
Be human.
Otherwise, they'll know.
Trust me, they'll know.
If you aren't honest, transparent and frank, you'll be dead to them.

Share everything!
Communicate transparently.

//Don't bore (or distract) the community with discussion of your product.
//It creates us vs them scenario.
//And never treat community as just another marketing channel.

Contributions should be for the good of the project, not self-centered on your product needs.
Otherwise, the changes are not in good faith.
Leave discussions about your product out of open source development.

If you're working for a company that sponsers an OSS project, don't let yourself get lost on the inside.
And do *not* have internal meetings to decide the fate of OSS.
//they'll know and it will destroy everything. (internal brainstorming is OK)
That's the quickest way to cause people to disassociate.

[discrete]
=== Recap

If you want to grow, you must connect with them.
To connect with them, you need to communicate with them and be present.
Without communication, it's just us vs them.
They remain outsiders.
With communication, you draw them in, get them to join your tribe.
// SLIDE IDEA: Tomitribe?

== Make people feel welcome
// Optimize for the first touch

Make people feel welcome.
Be all inclusive.
By making everyone feel welcome, you create a safe place for _anyone_ interested in the project to come, contribute, share their diverse talents and to be creative.

The first touch is them testing you.
They want to see how you respond and whether the community is a place they want to be.
You don't want to fail this test.
People are going to have questions, lots of them.
//!SLIDE ??? == Interest
Questions == interest.
Great questions (sometimes the best ones) look like dumb questions at first glance.
(Maybe a question that needs to be asked. Maybe even intentional).
No matter how silly that first question seems or how trivial the contribution, remember they could become the next leader of the project.
Or they could go contribute to some other project instead.
If their first touch is met with aversion or ridicule, the community will fail their test and they will withdraw.
You drove them away.

//!SLIDE Contributors, Please Use Other Front Door
//In order for your project to grow, people have to make it through the entryway of your project.
How many times have you come into a project and been told you started at the wrong place?
People rarely come through the main entrance.
The issue tracker, for example, is one of the most frequently used entry points into your project.
And the README? It should really be worth reading.
You never get a second chance to make a first impression.
In OSS, first impressions of your project matter a lot.

// FIXME isn't this redundant?
Newcomers only going to have so much fuel in the tank to make that initial contribution, so you need to lower barriers as much as possible.
Lower the barriers to entry (both for users and contributors); then lower them again, then again.
Every entrance, even the side doors, need to provide the full welcome mat experience.
Never forget to welcome them.
Optimize that first touch.

You should constantly be looking for newcomers.
Growth is when the number of people coming in exceeds the number going out.
That's why the first touch is so critical.
It should always be happening.

Formation and growth is a passionate ordeal, so people often come in “hot.”
Take this as a good sign for your project.
People are probably more frustrated than mad.
Give them outlets to channel that passion and turn it into productivity.
Your responsibility is to help them become a productive member of the community.
If they don't, you failed them, not the other way around.

// story about Prawn commit?

You will have dissenters.
Don't alienate or chastise them.
Assimilate them.
Do your best to turn their strengths into yours.

[discrete]
=== Choose civility

Keep in mind when you're interacting with people...

"You never lose points for professionalism."
-- Guy Martin

Treat everyone with respect.
Employees especially should be civil, no excuses.
Keep in mind that behind every <something> is a human being.
At the most extreme, communication should be technically brutal but personally respectful.

//Deter annoying contributors through delegation of work (they either back down or become productive)
//Only respond to the facts (people love to banter, but don't justify it with a response)

If the environment is closed or hostile, they'll leave.
(After all, they get enough politics at work).
If the environment is comfortable and makes them feel good, they'll not only stay, they'll invite others to join.
//and they'll  do their most creative work.

Promote diversity of all varieties in your community.
A Code of Conduct is advisable here.
People participate in open source for different reasons and at different levels.
You should know why each person participates, but remember there's no one right reason.
What matters is why they stay, why they choose to identify as members of your community.
Communities are in fact a network of (very) autonomous individuals.
//Remember that.

The tone you set for the community determines the fate of the community's health.
Put your best attitude forward.
*Choose civility.*

// M = mastery
== Recognize contributors and acknowledge their work
// faces, faces, faces screenshot

Once you receive a contribution, acknowledge it!
Being thanked feels good.
Every time.
People don't fill up on gratitude.
//There is no quota on appreciation.
No one says, “I don't need any more thanks, I'm good.”
Express your appreciation _generously_ and _sincerely_.
You should be doing it so much you might as well put a key on your keyboard for it.
//A sign of doing it right is that you'll know the usernames of all your community members by heart.

Let contributors know you see them;
that you appreciate their work;
that it matters to have them around.
There are no secrets here.
Even with the cards face up on table this still works.
When you appreciate them and their work, contributors will choose to stay and repeat the virtuous cycle.

//SLIDE! “I see you.”
[verse]
I see you.
I recognize your effort.
I value your contribution.
You have ownership.

Recognizing people also helps them stay motivated; to meet their purpose; affirms their goals.
It's positive reinforcement.
You recognize that the contributor has a place in the community and recognizes his/her role.
And it's *easy*, so there's just no reason to not do it.

//not doing this can make the experience detrimental for the contributor, and detrimental to your growth

//SLIDE! Bartosz@Devoxx (once we get to that part in the story)
.Bartosz story
//http://blog.bartoszmajsak.com/blog/2013/11/24/my-devoxx-experience/
// moral: believe in them before they are prepared to believe in themselves
****
I've been working with OSS communities for a long time.
But I could never quite put my finger on why one community works and another doesn't.
What is it all about?
//What is the true meaning of community?
...until right here in Antwerp during Devoxx 2013.

Two years earlier, Aslak Knutsen and I were walking along with a newcomer to the Arquillian community, Bartosz Majsak.
We arrived at the restaurant where we were going to eat and asked him to join us.
He said, “I have to go. I'm not a speaker like you guys.” and walked off.
Aslak and I looked at each other with a confused look, then immediately agreed that just wasn't going to fly and Aslak ran and got him.
He was just as much a part of Arquillian as either of us.

Fast-forward two years and Bartosz had become a speaker at Devoxx. A Devoxxian.
//He was sharing...
We were all rooming together, but left the apartment at different times that morning (why Bartosz wasn't with us when we left the apartment is another story you can ask me about later).
I attended another talk before Bartosz's and was chatting with someone in the corridor afterwards, so I was a few minutes late getting to Bartosz's talk.
As I entered the room, the room monitor looked at me shaking her head and mumbled, it's pretty full in there (good luck finding a seat).
I had to step over people standing in the entranceway to get close enough to see Bartosz on stage.
The theatre was completely packed.

Two years earlier, Bartosz viewed himself as just someone in the crowd, not worthy so to speak, and now, as a leader of the Arquillian project, I could barely get into the room to see him speak.
We believed in him before he was ready to believe in himself and now he had become a star.
But that's not even the most amazing part.
The focus of his talk was to encourage others to get involved with open source because it can change your life and career, as it did for him.
About half way through the talk, he put up names and faces of other open source contributors on the screen and he said, "these are the people that inspire me".
But those people weren't the leaders of the project, they were other community members.
Amazingly, even though he only had a “quicky” time slot (15 minutes), he gave up the stage for the last 5 minutes of the presentation to give a developer working on Mifos (an open source microfinance platform for developing countries) to talk about his project. 
Rather than use the stage to talk about himself, Bartosz had chosen to shine light on the work of others.
I was totally choked up.

I realized that this is what makes community work.
This is what makes it grow.
And this is what it's all about.
Directing the limelight and shining light on people that should be recognized, but aren't yet.
Making opportunities for others.

Bartosz had responded to the call to grow the community and become a mirror.

What's good for the community members is good for the project.
In 2012, Bartosz received a JBoss Community Award for his work on Arquillian and last year became the community manager for Arquillian.
Today, Alex Soto, one of the faces on Bartosz' slide, is the lead of the Arquillian Cube project and co-author of Arquillian in Action and also a Devoxxian.
By passing on these opportunities, you invest in the project's future and build a devoted community.
And it starts with the project leadership.
****

// FIXME consolidate with some of the points at the end of the Bartosz story
Recognition is something to be passed on.
Each leader has recognition to share.
They should act as a mirror (or mirror ball).
Reflect the light on the people that deserve it.
//Connect the people recognizing w/ the people to be recognized.
In doing so, they orchestrate the growth of the community.
//Creates an special atmosphere
“He who receives an idea from me, receives instruction himself without lessening mine; as he who lights his [candle] at mine, receives light without darkening me.” -- Thomas Jefferson
//”That ideas should freely spread from one to another over the globe...seems to have been peculiarly and benevolently designed by nature.” -- Thomas Jefferson

Once the community is committed to growing the community, then growth will happen.
It has to happen for a community to grow.
Recognizing people sustains the community.
Championing them grows it.

This is the key to growing OSS.
This is the key to growing a community.
This is the key to generating passion and devotion.
If you don't do it, you'll stagnate.
If you do it, you'll grow exponentially.

////
=== Encourage them
// be their mentor

Believe in them before they are prepared to believe in themselves.
////

// A = autonomy
== Elevate contributors to leaders
// also, give them space (let up on the gas)

One of the best ways to show appreciation to someone is to trust them.
That means giving them responsibility.

//SLIDE! Gripping edge of pool
OSS is about _not_ doing it alone.
Ask yourself if you're a ”wallflower” project.
//Do you have a “wallflower” project?
As the project and its community grows, you'll need to distribute the load.
That means you'll need to let go of control.
Otherwise, you'll be confined to going only where the edge can take you.
//If you don't move away from the wall, then it's not really open source; you don't benefit from it being open source.
I know that sounds scary.
But this is your chance to share opportunity with contributors and make them more autonomous.
And there are ways to make it much less scary.

Leverage automation to be there when you can't.
I don't do it enough.
You don't do it enough.
Automate liberally.
Automate validation.
Automate tests.
Automate workflow.
Automate releases.
Automate, automate, automate.
This lets you maintain quality, scope and purpose without always having to be on.
Leverage computation.
Make the computer do the work for you.
Never let it be idle.
Why should it?

With automation in place, you can start to empower people to take responsibility.
“empowerment of individuals is a key part of what makes open source work” -- Tim O'Reilly
Promote contributors to leaders.
Trust creates leaders, and leaders become heroes.
Everyone brings a unique skillset to the table.
The more autonomous the community, the more the unique skills are magnified and compounded.
Find the right people to lead each segment of the project and/or community and thus make it sustainable.

How do you get them to step up?

Every athlete you can think of has had a coach.
Coaches help us believe in ourselves before we are ready to.
They are our mentor.
As a community leader, you are the community's mentor.
Encourage them.
Guide them.
Nudge them.
Help them become productive members of the community.
Then, show them that what they do matters and empower them.

"Encouragement is oxygen for the soul."
-- Unknown

Delegating brings you relief and lets you escape the bus factor.
It not only frees up time, but it welcomes new ideas and growth.

//!SLIDE project stuck behind display case, breaking out
In fact, no other way is sustainable.
//do you have a look don't touch scenario?
Get your project out from behind the display case and into the hands of contributors.
Give them ownership.
//its a critical part of being a good citizen of open source.

//== Celebrate and share the prosperity
== Share the prosperity
// sharing is caring
// *Reinvest!*

Success.
That's the business you're in.
And that's the business you should be in for your community.
Success is infectious.
If people see their peers being celebrated and achieving success for participating in your community, they'll want to be a part of it too.
The success of the community directly translates into the success of the project and, in turn, the success of your business.
//Make them successful; only then can and will they make you successful; be passionate about this commitment
//make or break

These days, everyone's talking about being innovative.
“It's not enough to just have a good idea. Only when you act, when you implement, do you truly innovate.” -- Tom Kelley
A strong community fosters creativity and is hospitable to a culture of innovation.
//It also puts you in a great position to pivot if necessary because you have a healthy development group.
//Self-sustainable / scales
//Efficient
Growth pushes you to be better and proves that you can scale.

A successful community becomes your brand and your voice.
It builds your reputation, validates the technology and instills confidence in your company and its products and services.
In a way, a large, healthy community is like a ton of positive reviews on a product. It feels safe for people to adopt.
By doing OSS well, you stand to gain _trust_, _loyalty_ & _growth_.

////
.Vituous cycle of OSS; all roads point to you; anyone can play any role
      |
      v
 --> you <--
   /  ^
  |   |
  |
  \ 
   ~-> anyone associated with you
////

//you must then be a responsible citizen of open source
//fulfill your side of the contract & get a contract extension

After all, you're in Open Source to gain that competitive edge.
To be respected.
To stand out from the crowd.
To make others around you successful.
To benefit from ideas that come from left field.
That's where your future is.
//Don't ignore your positioning

It's going to be tempting when you become successful to forget about the community, leave them behind or take them for granted.
But you should be very careful to never let that happen.
Resist the urge to be above the community.
You can never forget about them because they are part of it.
//You've given them ownership.

//You can think of it like having children.
//Before, your world was just about you.
//But then you're responsible for another human life and they'll always be a part of everything you do.

It's also part of being a good citizen of open source and upholding your part of the contract.
They helped you create the software.
They have ownership.
You need to honor & respect their position.
They have a seat at the table.
Include them.
Maybe not any one individual, but certainly the community as a whole.

Sharing prosperity builds the ethos that enables the project to be sustainable long term.
Watch how you socialize at events like this one.
You should engage with newcomers like Bartosz once was as well as those that are seasoned.
//You should include community members whether they are new or seasoned.
//You're all part of the same tribe.
If you share your success--pass it on--community members from one generation pass on their success to the next, just like Bartosz has done.

In summary, you should always be *reinvesting* in the community.
If you're a company that uses open source, for heaven sakes, let your developers work on it.
“the best developers want to work on open code: to hire quality developers, give them an open source outlet”

The virtuous cycle that grows open source:

            Recruit
              __
            /    \
   Empower |      | Recognize
            \ __ /
            Encourage

//recruit: beer
//mentor: university
//encourage: thumbs up
//empower: graduation-cap or trophy or rocket or hand-o-up

      ↓
   ⇾ you ⇽
   /  ↑
  |
   \ ⇾ anyone associated with you

You want contributors to be successful because they choose to join your community, and you want others to see that.
That's how you grow.
//esp people that can't or work for your company; being part of the community gives you a way to share the prosperity.
//Better jobs, better pay, more leadership, promotions, more power
//Always be on the lookout for opportunities for contributors and connect them to those opportunities when they arise.
//Promote their work.
//Be their advocate.
//You know how your contributors work better than most, so you're in a great position to tell others about their skill set, work ethic and passion.

_Thank you and good luck.
Namaste._

////
== Arquillian translation story

Why would anyone work on a translation?
Isn't that something you just have to hire out?
Community proved that assumption wrong. Dead wrong.

Sense of pride in language.
Gave people, particuarly notable and influential people for that matter, an opportunity to become part of it.
Gave us a chance to recognize their work; somewhere to shine the limelight.

The Arquillian Getting Started guide is now translated in 12 languages.
And if you look at the names of the translators, you will recognize most of them.
Heroes.

== Other stories

* AsciidoctorJ
* Asciidoctor Chrome extension
* Arquillian Cube
* Tomitribe?
/////
